CREATE TABLE PUBLIC.PRODUCT(
   ID bigint PRIMARY KEY auto_increment,
   CATEGORY varchar(255) NOT NULL,
   NAME varchar(255) NOT NULL,
   ROLE_END timestamp,
   ROLE_START timestamp NOT NULL,
   SUB_CATEGORY varchar(255) NOT NULL,
   TYPE_ID bigint NOT NULL
);

CREATE INDEX PRODUCT_INDEX_TYPE ON PUBLIC.PRODUCT(TYPE_ID);
CREATE UNIQUE INDEX PRODUCT_INDEX ON PUBLIC.PRODUCT(ID);

CREATE TABLE PUBLIC.PRODUCT_TYPE
(
   ID bigint PRIMARY KEY auto_increment,
   DESCRIPTION varchar(255) NOT NULL,
   TYPE varchar(255) NOT NULL
);
CREATE UNIQUE INDEX PRODUCT_TYPE_INDEX ON PUBLIC.PRODUCT_TYPE(ID);

ALTER TABLE PUBLIC.PRODUCT
ADD CONSTRAINT PRODUCT_PRODUCT_TYPE
FOREIGN KEY (TYPE_ID)
REFERENCES PUBLIC.PRODUCT_TYPE(ID);
