INSERT INTO PRODUCT_TYPE (TYPE,DESCRIPTION) VALUES ('T1','Product type T1');
INSERT INTO PRODUCT_TYPE (TYPE,DESCRIPTION) VALUES ('X1','Test product');
INSERT INTO PRODUCT_TYPE (TYPE,DESCRIPTION) VALUES ('R3','Retail Three');
INSERT INTO PRODUCT_TYPE (TYPE,DESCRIPTION) VALUES ('R4','Retail Four');
INSERT INTO PRODUCT_TYPE (TYPE,DESCRIPTION) VALUES ('R5','Retail Five');
